/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package protein_structural_autoencoder;

import org.junit.jupiter.api.Test;

import protein_structural_autoencoder.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void someLibraryMethodReturnsTrue() {
        App classUnderTest = new App();
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
